### ISSUE TITLE
Check compatability with Feather:bit

### ISSUE THREAD

**Issue by samuk** [hansj66/micro-bot#1]
So I made a thing: https://github.com/rosmo-robot/Feather-Bit/tree/main/v1

When I get some made shall I post you one to see if it works in micro-bot?

**Comment by hansj66** [comment]
> So I made a thing: https://github.com/rosmo-robot/Feather-Bit/tree/main/v1

Nice :)
> When I get some made shall I post you one to see if it works in micro-bot?

Sure. I can test it out in one of the sumo bots .

**Comment by samuk** [comment]
Nice, I've found your email now. I'll drop you a mail when they arrive

**Comment by samuk** [comment]
Actually I don't see your email. Is there a way of getting it please?
